2024-12-02 22:00:48,288 - INFO - Using device: cpu
2024-12-02 22:00:48,288 - INFO - Loading data...
2024-12-02 22:00:48,446 - INFO - Data loaded successfully
2024-12-02 22:00:48,446 - INFO - Initializing model...
2024-12-02 22:00:52,557 - INFO - Starting training...
2024-12-02 22:00:52,572 - ERROR - An error occurred: 'int' object is not iterable
Traceback (most recent call last):
  File "e:\IUB\SEM_III\DLS\Final_Project\music_genre_classification\main.py", line 118, in main
    for batch in train_pbar:
  File "C:\Users\Manav\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\Manav\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Manav\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manav\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manav\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "e:\IUB\SEM_III\DLS\Final_Project\music_genre_classification\data_utils.py", line 40, in __getitem__
    [char for i, char in enumerate(numeric_part) if i == 0 or char != numeric_part[i-1]])
                         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
